version: "3"

services:
  app:
    build: .
    container_name: todo-app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todoapp
      - NODE_ENV=development
    ports:
      - "${PORT}:${PORT}" # host:container
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432" # host:container
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
